### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by sofushn** [sofushn/MovieSwipe#7]
Setup a database that can be used to store the app's data

### Tasks

- [ ] Setup Neo4J for storing data
- [ ] Integrate backend with Neo4J
- [ ] Import IMDb data dump ([link](https://www.imdb.com/interfaces/))
